generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\Finances2024
  packageName: Finances2024
files:
  api.mustache:
    templateType: API
    destinationFilename: /FinancesSDK2024.php
