<?php

/**
 * ItemFulfillment
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Plenty\AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Orders
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\Orders2026;

use ArrayAccess;
use Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ItemFulfillment implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ItemFulfillment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'quantity_fulfilled' => 'int',
        'quantity_unfulfilled' => 'int',
        'picking' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPicking::class,
        'packing' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPacking::class,
        'shipping' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemShipping::class
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'quantity_fulfilled' => null,
        'quantity_unfulfilled' => null,
        'picking' => null,
        'packing' => null,
        'shipping' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'quantity_fulfilled' => 'quantityFulfilled',
        'quantity_unfulfilled' => 'quantityUnfulfilled',
        'picking' => 'picking',
        'packing' => 'packing',
        'shipping' => 'shipping'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'quantity_fulfilled' => 'setQuantityFulfilled',
        'quantity_unfulfilled' => 'setQuantityUnfulfilled',
        'picking' => 'setPicking',
        'packing' => 'setPacking',
        'shipping' => 'setShipping'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'quantity_fulfilled' => 'getQuantityFulfilled',
        'quantity_unfulfilled' => 'getQuantityUnfulfilled',
        'picking' => 'getPicking',
        'packing' => 'getPacking',
        'shipping' => 'getShipping'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['quantity_fulfilled'] = $data['quantity_fulfilled'] ?? null;
        $this->container['quantity_unfulfilled'] = $data['quantity_unfulfilled'] ?? null;
        $this->container['picking'] = $data['picking'] ?? null;
        $this->container['packing'] = $data['packing'] ?? null;
        $this->container['shipping'] = $data['shipping'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets quantity_fulfilled
     *
     * @return int|null
     */
    public function getQuantityFulfilled()
    {
        return $this->container['quantity_fulfilled'];
    }

    /**
     * Sets quantity_fulfilled
     *
     * @param int|null $quantity_fulfilled The number of units of this item that have been successfully processed and shipped.
     *
     * @return self
     */
    public function setQuantityFulfilled($quantity_fulfilled): self
    {
        $this->container['quantity_fulfilled'] = $quantity_fulfilled;

        return $this;
    }

    /**
     * Gets quantity_unfulfilled
     *
     * @return int|null
     */
    public function getQuantityUnfulfilled()
    {
        return $this->container['quantity_unfulfilled'];
    }

    /**
     * Sets quantity_unfulfilled
     *
     * @param int|null $quantity_unfulfilled The number of units of this item that remain to be processed and shipped.
     *
     * @return self
     */
    public function setQuantityUnfulfilled($quantity_unfulfilled): self
    {
        $this->container['quantity_unfulfilled'] = $quantity_unfulfilled;

        return $this;
    }

    /**
     * Gets picking
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPicking|null
     */
    public function getPicking()
    {
        return $this->container['picking'];
    }

    /**
     * Sets picking
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPicking|null $picking picking
     *
     * @return self
     */
    public function setPicking($picking): self
    {
        $this->container['picking'] = $picking;

        return $this;
    }

    /**
     * Gets packing
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPacking|null
     */
    public function getPacking()
    {
        return $this->container['packing'];
    }

    /**
     * Sets packing
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPacking|null $packing packing
     *
     * @return self
     */
    public function setPacking($packing): self
    {
        $this->container['packing'] = $packing;

        return $this;
    }

    /**
     * Gets shipping
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemShipping|null
     */
    public function getShipping()
    {
        return $this->container['shipping'];
    }

    /**
     * Sets shipping
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemShipping|null $shipping shipping
     *
     * @return self
     */
    public function setShipping($shipping): self
    {
        $this->container['shipping'] = $shipping;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize(): string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
