<?php

/**
 * OrderItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Plenty\AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Orders
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\Orders2026;

use ArrayAccess;
use Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OrderItem implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'OrderItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'order_item_id' => 'string',
        'quantity_ordered' => 'int',
        'measurement' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\Measurement::class,
        'associated_order_items' => '\Plenty\AmazonPHP\SellingPartner\Model\Orders2026\AssociatedOrderItem[]',
        'programs' => 'string[]',
        'product' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProduct::class,
        'proceeds' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProceeds::class,
        'expense' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemExpense::class,
        'promotion' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPromotion::class,
        'cancellation' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemCancellation::class,
        'fulfillment' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemFulfillment::class,
        'tax' => \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemTax::class
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'order_item_id' => null,
        'quantity_ordered' => null,
        'measurement' => null,
        'associated_order_items' => null,
        'programs' => null,
        'product' => null,
        'proceeds' => null,
        'expense' => null,
        'promotion' => null,
        'cancellation' => null,
        'fulfillment' => null,
        'tax' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'order_item_id' => 'orderItemId',
        'quantity_ordered' => 'quantityOrdered',
        'measurement' => 'measurement',
        'associated_order_items' => 'associatedOrderItems',
        'programs' => 'programs',
        'product' => 'product',
        'proceeds' => 'proceeds',
        'expense' => 'expense',
        'promotion' => 'promotion',
        'cancellation' => 'cancellation',
        'fulfillment' => 'fulfillment',
        'tax' => 'tax'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'order_item_id' => 'setOrderItemId',
        'quantity_ordered' => 'setQuantityOrdered',
        'measurement' => 'setMeasurement',
        'associated_order_items' => 'setAssociatedOrderItems',
        'programs' => 'setPrograms',
        'product' => 'setProduct',
        'proceeds' => 'setProceeds',
        'expense' => 'setExpense',
        'promotion' => 'setPromotion',
        'cancellation' => 'setCancellation',
        'fulfillment' => 'setFulfillment',
        'tax' => 'setTax'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'order_item_id' => 'getOrderItemId',
        'quantity_ordered' => 'getQuantityOrdered',
        'measurement' => 'getMeasurement',
        'associated_order_items' => 'getAssociatedOrderItems',
        'programs' => 'getPrograms',
        'product' => 'getProduct',
        'proceeds' => 'getProceeds',
        'expense' => 'getExpense',
        'promotion' => 'getPromotion',
        'cancellation' => 'getCancellation',
        'fulfillment' => 'getFulfillment',
        'tax' => 'getTax'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order_item_id'] = $data['order_item_id'] ?? null;
        $this->container['quantity_ordered'] = $data['quantity_ordered'] ?? null;
        $this->container['measurement'] = $data['measurement'] ?? null;
        $this->container['associated_order_items'] = $data['associated_order_items'] ?? null;
        $this->container['programs'] = $data['programs'] ?? null;
        $this->container['product'] = $data['product'] ?? null;
        $this->container['proceeds'] = $data['proceeds'] ?? null;
        $this->container['expense'] = $data['expense'] ?? null;
        $this->container['promotion'] = $data['promotion'] ?? null;
        $this->container['cancellation'] = $data['cancellation'] ?? null;
        $this->container['fulfillment'] = $data['fulfillment'] ?? null;
        $this->container['tax'] = $data['tax'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['order_item_id'] === null) {
            $invalidProperties[] = "'order_item_id' can't be null";
        }
        if ($this->container['quantity_ordered'] === null) {
            $invalidProperties[] = "'quantity_ordered' can't be null";
        }
        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_item_id
     *
     * @return string
     */
    public function getOrderItemId()
    {
        return $this->container['order_item_id'];
    }

    /**
     * Sets order_item_id
     *
     * @param string $order_item_id A unique identifier for this specific item within the order.
     *
     * @return self
     */
    public function setOrderItemId($order_item_id): self
    {
        $this->container['order_item_id'] = $order_item_id;

        return $this;
    }

    /**
     * Gets quantity_ordered
     *
     * @return int
     */
    public function getQuantityOrdered()
    {
        return $this->container['quantity_ordered'];
    }

    /**
     * Sets quantity_ordered
     *
     * @param int $quantity_ordered The number of units of this item that the customer ordered.
     *
     * @return self
     */
    public function setQuantityOrdered($quantity_ordered): self
    {
        $this->container['quantity_ordered'] = $quantity_ordered;

        return $this;
    }

    /**
     * Gets measurement
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\Measurement|null
     */
    public function getMeasurement()
    {
        return $this->container['measurement'];
    }

    /**
     * Sets measurement
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\Measurement|null $measurement measurement
     *
     * @return self
     */
    public function setMeasurement($measurement): self
    {
        $this->container['measurement'] = $measurement;

        return $this;
    }

    /**
     * Gets associated_order_items
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\AssociatedOrderItem[]|null
     */
    public function getAssociatedOrderItems()
    {
        return $this->container['associated_order_items'];
    }

    /**
     * Sets associated_order_items
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\AssociatedOrderItem[]|null $associated_order_items A list of order items associated with this item. For example, a value-add service purchased with the product.
     *
     * @return self
     */
    public function setAssociatedOrderItems($associated_order_items): self
    {
        $this->container['associated_order_items'] = $associated_order_items;

        return $this;
    }

    /**
     * Gets programs
     *
     * @return string[]|null
     */
    public function getPrograms()
    {
        return $this->container['programs'];
    }

    /**
     * Sets programs
     *
     * @param string[]|null $programs Special programs that apply specifically to this item within the order.  **Possible values**: `TRANSPARENCY`, `SUBSCRIBE_AND_SAVE`
     *
     * @return self
     */
    public function setPrograms($programs): self
    {
        $this->container['programs'] = $programs;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProduct
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProduct $product product
     *
     * @return self
     */
    public function setProduct($product): self
    {
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets proceeds
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProceeds|null
     */
    public function getProceeds()
    {
        return $this->container['proceeds'];
    }

    /**
     * Sets proceeds
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemProceeds|null $proceeds proceeds
     *
     * @return self
     */
    public function setProceeds($proceeds): self
    {
        $this->container['proceeds'] = $proceeds;

        return $this;
    }

    /**
     * Gets expense
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemExpense|null
     */
    public function getExpense()
    {
        return $this->container['expense'];
    }

    /**
     * Sets expense
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemExpense|null $expense expense
     *
     * @return self
     */
    public function setExpense($expense): self
    {
        $this->container['expense'] = $expense;

        return $this;
    }

    /**
     * Gets promotion
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPromotion|null
     */
    public function getPromotion()
    {
        return $this->container['promotion'];
    }

    /**
     * Sets promotion
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemPromotion|null $promotion promotion
     *
     * @return self
     */
    public function setPromotion($promotion): self
    {
        $this->container['promotion'] = $promotion;

        return $this;
    }

    /**
     * Gets cancellation
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemCancellation|null
     */
    public function getCancellation()
    {
        return $this->container['cancellation'];
    }

    /**
     * Sets cancellation
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemCancellation|null $cancellation cancellation
     *
     * @return self
     */
    public function setCancellation($cancellation): self
    {
        $this->container['cancellation'] = $cancellation;

        return $this;
    }

    /**
     * Gets fulfillment
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemFulfillment|null
     */
    public function getFulfillment()
    {
        return $this->container['fulfillment'];
    }

    /**
     * Sets fulfillment
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemFulfillment|null $fulfillment fulfillment
     *
     * @return self
     */
    public function setFulfillment($fulfillment): self
    {
        $this->container['fulfillment'] = $fulfillment;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemTax|null
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\Orders2026\ItemTax|null $tax tax
     *
     * @return self
     */
    public function setTax($tax): self
    {
        $this->container['tax'] = $tax;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize(): string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
