<?php
/**
 * Charge
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;

use \ArrayAccess;
use \Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use \Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Charge implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Charge';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'base_charge' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup',
        'tax_breakup' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax[]',
        'charge_type' => 'string',
        'total_charge' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup',
        'total_tax' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'base_charge' => null,
        'tax_breakup' => null,
        'charge_type' => null,
        'total_charge' => null,
        'total_tax' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'base_charge' => 'baseCharge',
        'tax_breakup' => 'taxBreakup',
        'charge_type' => 'chargeType',
        'total_charge' => 'totalCharge',
        'total_tax' => 'totalTax'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'base_charge' => 'setBaseCharge',
        'tax_breakup' => 'setTaxBreakup',
        'charge_type' => 'setChargeType',
        'total_charge' => 'setTotalCharge',
        'total_tax' => 'setTotalTax'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'base_charge' => 'getBaseCharge',
        'tax_breakup' => 'getTaxBreakup',
        'charge_type' => 'getChargeType',
        'total_charge' => 'getTotalCharge',
        'total_tax' => 'getTotalTax'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    const CHARGE_TYPE_PRODUCT = 'PRODUCT';
    const CHARGE_TYPE_SHIPPING = 'SHIPPING';
    const CHARGE_TYPE_GIFT_WRAP = 'GIFT_WRAP';
    const CHARGE_TYPE_TOTAL = 'TOTAL';
    const CHARGE_TYPE_OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChargeTypeAllowableValues() : array
    {
        return [
            self::CHARGE_TYPE_PRODUCT,
            self::CHARGE_TYPE_SHIPPING,
            self::CHARGE_TYPE_GIFT_WRAP,
            self::CHARGE_TYPE_TOTAL,
            self::CHARGE_TYPE_OTHER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['base_charge'] = $data['base_charge'] ?? null;
        $this->container['tax_breakup'] = $data['tax_breakup'] ?? null;
        $this->container['charge_type'] = $data['charge_type'] ?? null;
        $this->container['total_charge'] = $data['total_charge'] ?? null;
        $this->container['total_tax'] = $data['total_tax'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['base_charge'] === null) {
            $invalidProperties[] = "'base_charge' can't be null";
        }
        if (!is_null($this->container['tax_breakup']) && (count($this->container['tax_breakup']) < 1)) {
            $invalidProperties[] = "invalid value for 'tax_breakup', number of items must be greater than or equal to 1.";
        }

        if ($this->container['charge_type'] === null) {
            $invalidProperties[] = "'charge_type' can't be null";
        }
        $allowedValues = $this->getChargeTypeAllowableValues();
        if (!is_null($this->container['charge_type']) && !in_array($this->container['charge_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'charge_type', must be one of '%s'",
                $this->container['charge_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['total_charge'] === null) {
            $invalidProperties[] = "'total_charge' can't be null";
        }
        if ($this->container['total_tax'] === null) {
            $invalidProperties[] = "'total_tax' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets base_charge
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup
     */
    public function getBaseCharge()
    {
        return $this->container['base_charge'];
    }

    /**
     * Sets base_charge
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup $base_charge base_charge
     *
     * @return self
     */
    public function setBaseCharge($base_charge) : self
    {
        $this->container['base_charge'] = $base_charge;

        return $this;
    }

    /**
     * Gets tax_breakup
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax[]|null
     */
    public function getTaxBreakup()
    {
        return $this->container['tax_breakup'];
    }

    /**
     * Sets tax_breakup
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax[]|null $tax_breakup The tax charge details.
     *
     * @return self
     */
    public function setTaxBreakup($tax_breakup) : self
    {


        if (!is_null($tax_breakup) && (count($tax_breakup) < 1)) {
            throw new \InvalidArgumentException('invalid length for $tax_breakup when calling Charge., number of items must be greater than or equal to 1.');
        }
        $this->container['tax_breakup'] = $tax_breakup;

        return $this;
    }

    /**
     * Gets charge_type
     *
     * @return string
     */
    public function getChargeType()
    {
        return $this->container['charge_type'];
    }

    /**
     * Sets charge_type
     *
     * @param string $charge_type The type of charge.
     *
     * @return self
     */
    public function setChargeType($charge_type) : self
    {
        $allowedValues = $this->getChargeTypeAllowableValues();
        if (!in_array($charge_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'charge_type', must be one of '%s'",
                    $charge_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['charge_type'] = $charge_type;

        return $this;
    }

    /**
     * Gets total_charge
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup
     */
    public function getTotalCharge()
    {
        return $this->container['total_charge'];
    }

    /**
     * Sets total_charge
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ChargeBreakup $total_charge total_charge
     *
     * @return self
     */
    public function setTotalCharge($total_charge) : self
    {
        $this->container['total_charge'] = $total_charge;

        return $this;
    }

    /**
     * Gets total_tax
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax
     */
    public function getTotalTax()
    {
        return $this->container['total_tax'];
    }

    /**
     * Sets total_tax
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Tax $total_tax total_tax
     *
     * @return self
     */
    public function setTotalTax($total_tax) : self
    {
        $this->container['total_tax'] = $total_tax;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
