<?php
/**
 * PackageStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;
use \Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use \Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 */
class PackageStatus
{
    /**
     * Possible values of this enum
     */
    const CREATED = 'CREATED';

    const PICKUP_SLOT_RETRIEVED = 'PICKUP_SLOT_RETRIEVED';

    const INVOICE_GENERATED = 'INVOICE_GENERATED';

    const SHIPLABEL_GENERATED = 'SHIPLABEL_GENERATED';

    const SHIPPED = 'SHIPPED';

    const DELIVERED = 'DELIVERED';

    private string $value;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::PICKUP_SLOT_RETRIEVED,
            self::INVOICE_GENERATED,
            self::SHIPLABEL_GENERATED,
            self::SHIPPED,
            self::DELIVERED
        ];
    }

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function toString(): string
    {
        return $this->value;
    }
}

