<?php
/**
 * PackageShipLabel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;

use \ArrayAccess;
use \Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use \Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PackageShipLabel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PackageShipLabel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'package_id' => 'string',
        'ship_label_metadata' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ShipLabelMetadata',
        'file_data' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\DocumentV2',
        'status' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Status',
        'error_details' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Error'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'package_id' => null,
        'ship_label_metadata' => null,
        'file_data' => null,
        'status' => null,
        'error_details' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'package_id' => 'packageId',
        'ship_label_metadata' => 'shipLabelMetadata',
        'file_data' => 'fileData',
        'status' => 'status',
        'error_details' => 'errorDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'package_id' => 'setPackageId',
        'ship_label_metadata' => 'setShipLabelMetadata',
        'file_data' => 'setFileData',
        'status' => 'setStatus',
        'error_details' => 'setErrorDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'package_id' => 'getPackageId',
        'ship_label_metadata' => 'getShipLabelMetadata',
        'file_data' => 'getFileData',
        'status' => 'getStatus',
        'error_details' => 'getErrorDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['package_id'] = $data['package_id'] ?? null;
        $this->container['ship_label_metadata'] = $data['ship_label_metadata'] ?? null;
        $this->container['file_data'] = $data['file_data'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['error_details'] = $data['error_details'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets package_id
     *
     * @return string|null
     */
    public function getPackageId()
    {
        return $this->container['package_id'];
    }

    /**
     * Sets package_id
     *
     * @param string|null $package_id The package ID of the package.
     *
     * @return self
     */
    public function setPackageId($package_id) : self
    {
        $this->container['package_id'] = $package_id;

        return $this;
    }

    /**
     * Gets ship_label_metadata
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ShipLabelMetadata|null
     */
    public function getShipLabelMetadata()
    {
        return $this->container['ship_label_metadata'];
    }

    /**
     * Sets ship_label_metadata
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ShipLabelMetadata|null $ship_label_metadata ship_label_metadata
     *
     * @return self
     */
    public function setShipLabelMetadata($ship_label_metadata) : self
    {
        $this->container['ship_label_metadata'] = $ship_label_metadata;

        return $this;
    }

    /**
     * Gets file_data
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\DocumentV2|null
     */
    public function getFileData()
    {
        return $this->container['file_data'];
    }

    /**
     * Sets file_data
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\DocumentV2|null $file_data file_data
     *
     * @return self
     */
    public function setFileData($file_data) : self
    {
        $this->container['file_data'] = $file_data;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Status|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Status|null $status status
     *
     * @return self
     */
    public function setStatus($status) : self
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets error_details
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Error|null
     */
    public function getErrorDetails()
    {
        return $this->container['error_details'];
    }

    /**
     * Sets error_details
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Error|null $error_details error_details
     *
     * @return self
     */
    public function setErrorDetails($error_details) : self
    {
        $this->container['error_details'] = $error_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
