<?php
/**
 * ReplacedShipmentInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;

use \ArrayAccess;
use \Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use \Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ReplacedShipmentInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ReplacedShipmentInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'location_id' => 'string',
        'marketplace_attributes' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\MarketplaceAttributes',
        'original_line_items' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\OriginalLineItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'location_id' => null,
        'marketplace_attributes' => null,
        'original_line_items' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'location_id' => 'locationId',
        'marketplace_attributes' => 'marketplaceAttributes',
        'original_line_items' => 'originalLineItems'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'id' => 'setId',
        'location_id' => 'setLocationId',
        'marketplace_attributes' => 'setMarketplaceAttributes',
        'original_line_items' => 'setOriginalLineItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'id' => 'getId',
        'location_id' => 'getLocationId',
        'marketplace_attributes' => 'getMarketplaceAttributes',
        'original_line_items' => 'getOriginalLineItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['location_id'] = $data['location_id'] ?? null;
        $this->container['marketplace_attributes'] = $data['marketplace_attributes'] ?? null;
        $this->container['original_line_items'] = $data['original_line_items'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['location_id'] === null) {
            $invalidProperties[] = "'location_id' can't be null";
        }
        if ($this->container['marketplace_attributes'] === null) {
            $invalidProperties[] = "'marketplace_attributes' can't be null";
        }
        if (!is_null($this->container['original_line_items']) && (count($this->container['original_line_items']) < 1)) {
            $invalidProperties[] = "invalid value for 'original_line_items', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The original shipment's ID.
     *
     * @return self
     */
    public function setId($id) : self
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets location_id
     *
     * @return string
     */
    public function getLocationId()
    {
        return $this->container['location_id'];
    }

    /**
     * Sets location_id
     *
     * @param string $location_id The original shipment's location ID.
     *
     * @return self
     */
    public function setLocationId($location_id) : self
    {
        $this->container['location_id'] = $location_id;

        return $this;
    }

    /**
     * Gets marketplace_attributes
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\MarketplaceAttributes
     */
    public function getMarketplaceAttributes()
    {
        return $this->container['marketplace_attributes'];
    }

    /**
     * Sets marketplace_attributes
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\MarketplaceAttributes $marketplace_attributes marketplace_attributes
     *
     * @return self
     */
    public function setMarketplaceAttributes($marketplace_attributes) : self
    {
        $this->container['marketplace_attributes'] = $marketplace_attributes;

        return $this;
    }

    /**
     * Gets original_line_items
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\OriginalLineItem[]|null
     */
    public function getOriginalLineItems()
    {
        return $this->container['original_line_items'];
    }

    /**
     * Sets original_line_items
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\OriginalLineItem[]|null $original_line_items The line items from the original shipment that corresponds to this shipment.
     *
     * @return self
     */
    public function setOriginalLineItems($original_line_items) : self
    {


        if (!is_null($original_line_items) && (count($original_line_items) < 1)) {
            throw new \InvalidArgumentException('invalid length for $original_line_items when calling ReplacedShipmentInfo., number of items must be greater than or equal to 1.');
        }
        $this->container['original_line_items'] = $original_line_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
