<?php
/**
 * ShipmentLineItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ShipmentLineItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ShipmentLineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'shipment_line_item_id' => 'string',
        'merchant_sku' => 'string',
        'number_of_units' => 'int',
        'serial_numbers' => 'string[]',
        'piece_type' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\PieceType',
        'hazmat_labels' => 'string[]',
        'gift_attributes' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\GiftAttributes',
        'charges' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Charge[]',
        'cancellations' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Cancellation[]',
        'hsn_code' => 'string',
        'recommended_country_of_origin' => 'string',
        'country_of_origin' => 'string',
        'recommended_currency_code' => 'string',
        'item_value' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Amount',
        'compliance_attributes' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ComplianceAttributes',
        'custom_attributes' => '\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\CustomAttribute[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'shipment_line_item_id' => null,
        'merchant_sku' => null,
        'number_of_units' => null,
        'serial_numbers' => null,
        'piece_type' => null,
        'hazmat_labels' => null,
        'gift_attributes' => null,
        'charges' => null,
        'cancellations' => null,
        'hsn_code' => null,
        'recommended_country_of_origin' => null,
        'country_of_origin' => null,
        'recommended_currency_code' => null,
        'item_value' => null,
        'compliance_attributes' => null,
        'custom_attributes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'shipment_line_item_id' => 'shipmentLineItemId',
        'merchant_sku' => 'merchantSku',
        'number_of_units' => 'numberOfUnits',
        'serial_numbers' => 'serialNumbers',
        'piece_type' => 'pieceType',
        'hazmat_labels' => 'hazmatLabels',
        'gift_attributes' => 'giftAttributes',
        'charges' => 'charges',
        'cancellations' => 'cancellations',
        'hsn_code' => 'hsnCode',
        'recommended_country_of_origin' => 'recommendedCountryOfOrigin',
        'country_of_origin' => 'countryOfOrigin',
        'recommended_currency_code' => 'recommendedCurrencyCode',
        'item_value' => 'itemValue',
        'compliance_attributes' => 'complianceAttributes',
        'custom_attributes' => 'customAttributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'shipment_line_item_id' => 'setShipmentLineItemId',
        'merchant_sku' => 'setMerchantSku',
        'number_of_units' => 'setNumberOfUnits',
        'serial_numbers' => 'setSerialNumbers',
        'piece_type' => 'setPieceType',
        'hazmat_labels' => 'setHazmatLabels',
        'gift_attributes' => 'setGiftAttributes',
        'charges' => 'setCharges',
        'cancellations' => 'setCancellations',
        'hsn_code' => 'setHsnCode',
        'recommended_country_of_origin' => 'setRecommendedCountryOfOrigin',
        'country_of_origin' => 'setCountryOfOrigin',
        'recommended_currency_code' => 'setRecommendedCurrencyCode',
        'item_value' => 'setItemValue',
        'compliance_attributes' => 'setComplianceAttributes',
        'custom_attributes' => 'setCustomAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'shipment_line_item_id' => 'getShipmentLineItemId',
        'merchant_sku' => 'getMerchantSku',
        'number_of_units' => 'getNumberOfUnits',
        'serial_numbers' => 'getSerialNumbers',
        'piece_type' => 'getPieceType',
        'hazmat_labels' => 'getHazmatLabels',
        'gift_attributes' => 'getGiftAttributes',
        'charges' => 'getCharges',
        'cancellations' => 'getCancellations',
        'hsn_code' => 'getHsnCode',
        'recommended_country_of_origin' => 'getRecommendedCountryOfOrigin',
        'country_of_origin' => 'getCountryOfOrigin',
        'recommended_currency_code' => 'getRecommendedCurrencyCode',
        'item_value' => 'getItemValue',
        'compliance_attributes' => 'getComplianceAttributes',
        'custom_attributes' => 'getCustomAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipment_line_item_id'] = $data['shipment_line_item_id'] ?? null;
        $this->container['merchant_sku'] = $data['merchant_sku'] ?? null;
        $this->container['number_of_units'] = $data['number_of_units'] ?? null;
        $this->container['serial_numbers'] = $data['serial_numbers'] ?? null;
        $this->container['piece_type'] = $data['piece_type'] ?? null;
        $this->container['hazmat_labels'] = $data['hazmat_labels'] ?? null;
        $this->container['gift_attributes'] = $data['gift_attributes'] ?? null;
        $this->container['charges'] = $data['charges'] ?? null;
        $this->container['cancellations'] = $data['cancellations'] ?? null;
        $this->container['hsn_code'] = $data['hsn_code'] ?? null;
        $this->container['recommended_country_of_origin'] = $data['recommended_country_of_origin'] ?? null;
        $this->container['country_of_origin'] = $data['country_of_origin'] ?? null;
        $this->container['recommended_currency_code'] = $data['recommended_currency_code'] ?? null;
        $this->container['item_value'] = $data['item_value'] ?? null;
        $this->container['compliance_attributes'] = $data['compliance_attributes'] ?? null;
        $this->container['custom_attributes'] = $data['custom_attributes'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['shipment_line_item_id'] === null) {
            $invalidProperties[] = "'shipment_line_item_id' can't be null";
        }
        if ($this->container['merchant_sku'] === null) {
            $invalidProperties[] = "'merchant_sku' can't be null";
        }
        if ($this->container['number_of_units'] === null) {
            $invalidProperties[] = "'number_of_units' can't be null";
        }
        if (($this->container['number_of_units'] < 1)) {
            $invalidProperties[] = "invalid value for 'number_of_units', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['serial_numbers']) && (count($this->container['serial_numbers']) < 0)) {
            $invalidProperties[] = "invalid value for 'serial_numbers', number of items must be greater than or equal to 0.";
        }

        if (!is_null($this->container['hazmat_labels']) && (count($this->container['hazmat_labels']) < 0)) {
            $invalidProperties[] = "invalid value for 'hazmat_labels', number of items must be greater than or equal to 0.";
        }

        if ($this->container['charges'] === null) {
            $invalidProperties[] = "'charges' can't be null";
        }
        if ((count($this->container['charges']) < 1)) {
            $invalidProperties[] = "invalid value for 'charges', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['cancellations']) && (count($this->container['cancellations']) < 0)) {
            $invalidProperties[] = "invalid value for 'cancellations', number of items must be greater than or equal to 0.";
        }

        if ($this->container['compliance_attributes'] === null) {
            $invalidProperties[] = "'compliance_attributes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipment_line_item_id
     *
     * @return string
     */
    public function getShipmentLineItemId()
    {
        return $this->container['shipment_line_item_id'];
    }

    /**
     * Sets shipment_line_item_id
     *
     * @param string $shipment_line_item_id An identifier for a shipment's line item. This identifier is guaranteed to be unique within the scope of its containing shipment.
     *
     * @return self
     */
    public function setShipmentLineItemId($shipment_line_item_id) : self
    {
        $this->container['shipment_line_item_id'] = $shipment_line_item_id;

        return $this;
    }

    /**
     * Gets merchant_sku
     *
     * @return string
     */
    public function getMerchantSku()
    {
        return $this->container['merchant_sku'];
    }

    /**
     * Sets merchant_sku
     *
     * @param string $merchant_sku The seller SKU of a product (catalog item). A unique number assigned by the seller when listing an item.
     *
     * @return self
     */
    public function setMerchantSku($merchant_sku) : self
    {
        $this->container['merchant_sku'] = $merchant_sku;

        return $this;
    }

    /**
     * Gets number_of_units
     *
     * @return int
     */
    public function getNumberOfUnits()
    {
        return $this->container['number_of_units'];
    }

    /**
     * Sets number_of_units
     *
     * @param int $number_of_units The number of items of the SKU in this line item.
     *
     * @return self
     */
    public function setNumberOfUnits($number_of_units) : self
    {

        if (($number_of_units < 1)) {
            throw new \InvalidArgumentException('invalid value for $number_of_units when calling ShipmentLineItem., must be bigger than or equal to 1.');
        }

        $this->container['number_of_units'] = $number_of_units;

        return $this;
    }

    /**
     * Gets serial_numbers
     *
     * @return string[]|null
     */
    public function getSerialNumbers()
    {
        return $this->container['serial_numbers'];
    }

    /**
     * Sets serial_numbers
     *
     * @param string[]|null $serial_numbers The serial numbers for each item in this line item.
     *
     * @return self
     */
    public function setSerialNumbers($serial_numbers) : self
    {


        if (!is_null($serial_numbers) && (count($serial_numbers) < 0)) {
            throw new \InvalidArgumentException('invalid length for $serial_numbers when calling ShipmentLineItem., number of items must be greater than or equal to 0.');
        }
        $this->container['serial_numbers'] = $serial_numbers;

        return $this;
    }

    /**
     * Gets piece_type
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\PieceType|null
     */
    public function getPieceType()
    {
        return $this->container['piece_type'];
    }

    /**
     * Sets piece_type
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\PieceType|null $piece_type piece_type
     *
     * @return self
     */
    public function setPieceType($piece_type) : self
    {
        $this->container['piece_type'] = $piece_type;

        return $this;
    }

    /**
     * Gets hazmat_labels
     *
     * @return string[]|null
     */
    public function getHazmatLabels()
    {
        return $this->container['hazmat_labels'];
    }

    /**
     * Sets hazmat_labels
     *
     * @param string[]|null $hazmat_labels A list of HAZMAT label identifiers that must be applied to the packages for this line item.
     *
     * @return self
     */
    public function setHazmatLabels($hazmat_labels) : self
    {


        if (!is_null($hazmat_labels) && (count($hazmat_labels) < 0)) {
            throw new \InvalidArgumentException('invalid length for $hazmat_labels when calling ShipmentLineItem., number of items must be greater than or equal to 0.');
        }
        $this->container['hazmat_labels'] = $hazmat_labels;

        return $this;
    }

    /**
     * Gets gift_attributes
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\GiftAttributes|null
     */
    public function getGiftAttributes()
    {
        return $this->container['gift_attributes'];
    }

    /**
     * Sets gift_attributes
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\GiftAttributes|null $gift_attributes gift_attributes
     *
     * @return self
     */
    public function setGiftAttributes($gift_attributes) : self
    {
        $this->container['gift_attributes'] = $gift_attributes;

        return $this;
    }

    /**
     * Gets charges
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Charge[]
     */
    public function getCharges()
    {
        return $this->container['charges'];
    }

    /**
     * Sets charges
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Charge[] $charges The charges associated with the shipment.
     *
     * @return self
     */
    public function setCharges($charges) : self
    {


        if ((count($charges) < 1)) {
            throw new \InvalidArgumentException('invalid length for $charges when calling ShipmentLineItem., number of items must be greater than or equal to 1.');
        }
        $this->container['charges'] = $charges;

        return $this;
    }

    /**
     * Gets cancellations
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Cancellation[]|null
     */
    public function getCancellations()
    {
        return $this->container['cancellations'];
    }

    /**
     * Sets cancellations
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Cancellation[]|null $cancellations A list of cancellations for the given line item.  **Note:** Currently, SmartConnect does not support partial cancellation of a shipment or its line items. This list will contain a single value with all the cancellation details.
     *
     * @return self
     */
    public function setCancellations($cancellations) : self
    {


        if (!is_null($cancellations) && (count($cancellations) < 0)) {
            throw new \InvalidArgumentException('invalid length for $cancellations when calling ShipmentLineItem., number of items must be greater than or equal to 0.');
        }
        $this->container['cancellations'] = $cancellations;

        return $this;
    }

    /**
     * Gets hsn_code
     *
     * @return string|null
     */
    public function getHsnCode()
    {
        return $this->container['hsn_code'];
    }

    /**
     * Sets hsn_code
     *
     * @param string|null $hsn_code The HSN code of SKU in this line item.
     *
     * @return self
     */
    public function setHsnCode($hsn_code) : self
    {
        $this->container['hsn_code'] = $hsn_code;

        return $this;
    }

    /**
     * Gets recommended_country_of_origin
     *
     * @return string|null
     */
    public function getRecommendedCountryOfOrigin()
    {
        return $this->container['recommended_country_of_origin'];
    }

    /**
     * Sets recommended_country_of_origin
     *
     * @param string|null $recommended_country_of_origin A two-letter country code, as defined by the ISO-3166 alpha-2 standard.
     *
     * @return self
     */
    public function setRecommendedCountryOfOrigin($recommended_country_of_origin) : self
    {
        $this->container['recommended_country_of_origin'] = $recommended_country_of_origin;

        return $this;
    }

    /**
     * Gets country_of_origin
     *
     * @return string|null
     */
    public function getCountryOfOrigin()
    {
        return $this->container['country_of_origin'];
    }

    /**
     * Sets country_of_origin
     *
     * @param string|null $country_of_origin A two-letter country code, as defined by the ISO-3166 alpha-2 standard.
     *
     * @return self
     */
    public function setCountryOfOrigin($country_of_origin) : self
    {
        $this->container['country_of_origin'] = $country_of_origin;

        return $this;
    }

    /**
     * Gets recommended_currency_code
     *
     * @return string|null
     */
    public function getRecommendedCurrencyCode()
    {
        return $this->container['recommended_currency_code'];
    }

    /**
     * Sets recommended_currency_code
     *
     * @param string|null $recommended_currency_code The three digit currency code of the currency recommended by the marketplace, in ISO 4217 format.
     *
     * @return self
     */
    public function setRecommendedCurrencyCode($recommended_currency_code) : self
    {
        $this->container['recommended_currency_code'] = $recommended_currency_code;

        return $this;
    }

    /**
     * Gets item_value
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Amount|null
     */
    public function getItemValue()
    {
        return $this->container['item_value'];
    }

    /**
     * Sets item_value
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\Amount|null $item_value item_value
     *
     * @return self
     */
    public function setItemValue($item_value) : self
    {
        $this->container['item_value'] = $item_value;

        return $this;
    }

    /**
     * Gets compliance_attributes
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ComplianceAttributes
     */
    public function getComplianceAttributes()
    {
        return $this->container['compliance_attributes'];
    }

    /**
     * Sets compliance_attributes
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\ComplianceAttributes $compliance_attributes compliance_attributes
     *
     * @return self
     */
    public function setComplianceAttributes($compliance_attributes) : self
    {
        $this->container['compliance_attributes'] = $compliance_attributes;

        return $this;
    }

    /**
     * Gets custom_attributes
     *
     * @return \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\CustomAttribute[]|null
     */
    public function getCustomAttributes()
    {
        return $this->container['custom_attributes'];
    }

    /**
     * Sets custom_attributes
     *
     * @param \AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\CustomAttribute[]|null $custom_attributes A list of custom passthrough attributes. For details on these attributes, reach out to your respective program teams at Amazon.
     *
     * @return self
     */
    public function setCustomAttributes($custom_attributes) : self
    {
        $this->container['custom_attributes'] = $custom_attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
