<?php
/**
 * ShipLabelMetadata
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AmazonPHP\SellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024;

use \ArrayAccess;
use \Plenty\AmazonPHP\SellingPartner\ObjectSerializer;
use \Plenty\AmazonPHP\SellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ShipLabelMetadata implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ShipLabelMetadata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'shipping_option_id' => 'string',
        'carrier_name' => 'string',
        'tracking_id' => 'string',
        'pickup_window' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow',
        'time_slot' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow',
        'handover_location' => '\Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\HandoverLocation'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'shipping_option_id' => null,
        'carrier_name' => null,
        'tracking_id' => null,
        'pickup_window' => null,
        'time_slot' => null,
        'handover_location' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'shipping_option_id' => 'shippingOptionId',
        'carrier_name' => 'carrierName',
        'tracking_id' => 'trackingId',
        'pickup_window' => 'pickupWindow',
        'time_slot' => 'timeSlot',
        'handover_location' => 'handoverLocation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'shipping_option_id' => 'setShippingOptionId',
        'carrier_name' => 'setCarrierName',
        'tracking_id' => 'setTrackingId',
        'pickup_window' => 'setPickupWindow',
        'time_slot' => 'setTimeSlot',
        'handover_location' => 'setHandoverLocation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'shipping_option_id' => 'getShippingOptionId',
        'carrier_name' => 'getCarrierName',
        'tracking_id' => 'getTrackingId',
        'pickup_window' => 'getPickupWindow',
        'time_slot' => 'getTimeSlot',
        'handover_location' => 'getHandoverLocation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipping_option_id'] = $data['shipping_option_id'] ?? null;
        $this->container['carrier_name'] = $data['carrier_name'] ?? null;
        $this->container['tracking_id'] = $data['tracking_id'] ?? null;
        $this->container['pickup_window'] = $data['pickup_window'] ?? null;
        $this->container['time_slot'] = $data['time_slot'] ?? null;
        $this->container['handover_location'] = $data['handover_location'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['carrier_name'] === null) {
            $invalidProperties[] = "'carrier_name' can't be null";
        }
        if ($this->container['tracking_id'] === null) {
            $invalidProperties[] = "'tracking_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipping_option_id
     *
     * @return string|null
     */
    public function getShippingOptionId()
    {
        return $this->container['shipping_option_id'];
    }

    /**
     * Sets shipping_option_id
     *
     * @param string|null $shipping_option_id The selected slot for the ship label.
     *
     * @return self
     */
    public function setShippingOptionId($shipping_option_id) : self
    {
        $this->container['shipping_option_id'] = $shipping_option_id;

        return $this;
    }

    /**
     * Gets carrier_name
     *
     * @return string
     */
    public function getCarrierName()
    {
        return $this->container['carrier_name'];
    }

    /**
     * Sets carrier_name
     *
     * @param string $carrier_name The name of the carrier.
     *
     * @return self
     */
    public function setCarrierName($carrier_name) : self
    {
        $this->container['carrier_name'] = $carrier_name;

        return $this;
    }

    /**
     * Gets tracking_id
     *
     * @return string
     */
    public function getTrackingId()
    {
        return $this->container['tracking_id'];
    }

    /**
     * Sets tracking_id
     *
     * @param string $tracking_id The tracking number of the package.
     *
     * @return self
     */
    public function setTrackingId($tracking_id) : self
    {
        $this->container['tracking_id'] = $tracking_id;

        return $this;
    }

    /**
     * Gets pickup_window
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow|null
     */
    public function getPickupWindow()
    {
        return $this->container['pickup_window'];
    }

    /**
     * Sets pickup_window
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow|null $pickup_window pickup_window
     *
     * @return self
     */
    public function setPickupWindow($pickup_window) : self
    {
        $this->container['pickup_window'] = $pickup_window;

        return $this;
    }

    /**
     * Gets time_slot
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow|null
     */
    public function getTimeSlot()
    {
        return $this->container['time_slot'];
    }

    /**
     * Sets time_slot
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\TimeWindow|null $time_slot time_slot
     *
     * @return self
     */
    public function setTimeSlot($time_slot) : self
    {
        $this->container['time_slot'] = $time_slot;

        return $this;
    }

    /**
     * Gets handover_location
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\HandoverLocation|null
     */
    public function getHandoverLocation()
    {
        return $this->container['handover_location'];
    }

    /**
     * Sets handover_location
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\ExternalFulfillmentShipping2024\HandoverLocation|null $handover_location handover_location
     *
     * @return self
     */
    public function setHandoverLocation($handover_location) : self
    {
        $this->container['handover_location'] = $handover_location;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
